services:
  - type: web
    name: gestion-dettes
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/gestion-dettes-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
